# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8", # 4.7-inches
  "iPhone 8 Plus", # 5.5-inches
  "iPhone XS", # 5.8-inches
  "iPhone XS Max", # 6.5-inches
  "iPad Pro (12.9-inch)"
])

languages([
  "de-DE"
])

# The name of the scheme which contains the UI Tests
scheme("MakulaScreenshots")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
